version: '3.7'

services:

  app:
    image: gmorales256/crm-dockerized
    depends_on:
      - mysql
    ports:
      - '4000:4000'
    environment:
      MYSQL_DB: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql-data/:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
